const techSkillsArray = [
  "JavaScript",
  "Python",
  "Java",
  "C#",
  "Ruby",
  "PHP",
  "HTML/CSS",
  "React",
  "Angular",
  "Vue",
  "Node.js",
  "Django",
  "Flask",
  "Swift",
  "Kotlin",
  "SQL",
  "MongoDB",
  "Cassandra",
  "AWS",
  "Azure",
  "Google Cloud Platform",

  "Docker",
  "Kubernetes",
  "RESTful API design",
  "Server-side scripting",
  "Microservices architecture",
  "Git",
  "Network security",
  "Penetration testing",
  "Data analysis",
  "Machine learning",
  "Hadoop",
  "Spark",
  "TCP/IP",
  "Network protocols",
  "Routing and switching",
  "Test automation",
  "Selenium",
  "JUnit",
  "Agile methodologies",
  "Scrum",
  "Communication skills",
  "Problem-solving",
  "Collaboration and teamwork",
  "Data structures",
  "Algorithms",
  "npm",
  "Yarn",
  "Webpack",
  "Linux/Unix",
  "Command line",
  "System administration",
  "User interface design principles",
  "Sketch",
  "Figma",
];
export default techSkillsArray;
